id = "night-shift"
name = "Night Shift Theme"
schema_version = 1
version = "1.0.2"
authors = ["Jean Tinland"]
description = "A clean desatured zed theme"
repository = "https://github.com/Jean-Tinland/zed-theme-night-shift"
